version: "2.2"

services:
  nginx:
    image: nginx:alpine
    # cpus: 1
    pids_limit: 1024
    mem_limit: 1G
    memswap_limit: 1G
    ulimits:
      nofile:
        soft: 12000
        hard: 12000
    restart: always
    stop_grace_period: 3s
    ports:
      - "2048:2048"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./front:/var/www:ro
    networks:
      - internal
    depends_on:
      - executor
      - verifier

  executor:
    build: ./executor
    # cpus: 4
    pids_limit: 2048
    mem_limit: 2G
    ulimits:
      nofile:
        soft: 120000
        hard: 120000
    restart: always
    stop_grace_period: 1s
    volumes:
      - gatekeeper-executor:/var/gatekeeper/executor:rw
    networks:
      - internal
    environment:
      - VERIFIER_BASE_URL=http://verifier:2046/

  verifier:
    build: ./verifier
    # cpus: 4
    pids_limit: 2048
    mem_limit: 2G
    restart: always
    stop_grace_period: 1s
    volumes:
      - gatekeeper-verifier:/var/gatekeeper/verifier:rw
    networks:
      - internal
    environment:
      - VERIFIER_KEY_DIR=/var/gatekeeper/verifier/keys

  cleaner:
    build: ./cleaner
    # cpus: 1
    restart: always
    stop_grace_period: 1s
    networks:
      - internal
    volumes:
      - gatekeeper-executor:/var/gatekeeper/executor:rw

volumes:
  gatekeeper-executor:
  gatekeeper-verifier:

networks:
  internal:
    driver: bridge
